--- 
- name: This is first play 
  hosts: all
  tasks:
  - name: check if machine is reachable
    ping:
  - name: print message with debug module
    debug: 
      msg: "machine is reachable" 

- name: This is second play 
  become: true              # to give root access 
  hosts: all
  tasks:
  - name: create user
    user:
      name: user6
      state: present
...
